### ISSUE TITLE
Missing dosageInstruction in the MedicationOrder-s

### ISSUE THREAD

**Issue by nschwertner** [smart-on-fhir/hca-fhir-importer#1]
See https://github.com/smart-on-fhir/smart-stub/issues/1

**Comment by p2** [comment]
Well, `dosageInstruction` on _MedicationOrder_ is not mandatory. We don't have instructions for the meds, we just know that they're taking this medication.

**Comment by nschwertner** [comment]
Sure, it's not mandatory in FHIR, but I am not sure about SMART. The way the spec (http://docs.smarthealthit.org/profiles/) reads, it seems like `dosageInstruction` may be mandatory. If it is, then we need to fix the HCA patients. Otherwise, we can blame Diabetes Monograph for assuming `dosageInstruction` and crashing when it's not there. Josh (@jmandel), how should we interpret the spec?

**Comment by p2** [comment]
Don't these only apply to `dosageInstruction` that are actually present? I don't think that means there has to be one.

**Comment by jmandel** [comment]
While I'd love to say "we always have dosage instructions", the fact that
is they may not always be available, especially when extracting/mining
legacy data.

**Comment by p2** [comment]
I'm also thinking that for most CDS use cases, one wants to use `MedicationOrder` but does not care about the instructions.

**Comment by jmandel** [comment]
Oh, that depends. For _some_ CDS use cases, sure. But dose checking, or price estimation for example... :-)

**Comment by p2** [comment]
Fine. _Some_ it is. :)

**Comment by nschwertner** [comment]
Ok, so, then we will let Diabetes Monograph be as it may
